# Generated by Django 3.0.7 on 2020-07-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='phon',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
